/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIJAY MORE
 */
public class Officer_home_page extends javax.swing.JFrame {

    /**
     * Creates new form Officer_home_page
     */
    public Officer_home_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Addsuspect = new javax.swing.JButton();
        Addsuspect1 = new javax.swing.JButton();
        Addsuspect2 = new javax.swing.JButton();
        Addsuspect3 = new javax.swing.JButton();
        Addsuspect4 = new javax.swing.JButton();
        Addsuspect5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\VIJAY MORE\\Desktop\\dimple vjti notes\\third year\\lab\\SE\\Final.jpg")); // NOI18N

        jTextField1.setBackground(new java.awt.Color(0, 0, 204));
        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 255, 255));
        jTextField1.setText("INVESTIGATION BUREAU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextField1)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 100);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Addsuspect.setBackground(new java.awt.Color(153, 153, 153));
        Addsuspect.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Addsuspect.setText("Add Suspect");
        Addsuspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddsuspectActionPerformed(evt);
            }
        });

        Addsuspect1.setBackground(new java.awt.Color(153, 153, 153));
        Addsuspect1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Addsuspect1.setText("Add Evidence");
        Addsuspect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addsuspect1ActionPerformed(evt);
            }
        });

        Addsuspect2.setBackground(new java.awt.Color(153, 153, 153));
        Addsuspect2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Addsuspect2.setText("View Suspect");
        Addsuspect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addsuspect2ActionPerformed(evt);
            }
        });

        Addsuspect3.setBackground(new java.awt.Color(153, 153, 153));
        Addsuspect3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Addsuspect3.setText("View Case History");
        Addsuspect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addsuspect3ActionPerformed(evt);
            }
        });

        Addsuspect4.setBackground(new java.awt.Color(153, 153, 153));
        Addsuspect4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Addsuspect4.setText("View Evidence");
        Addsuspect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addsuspect4ActionPerformed(evt);
            }
        });

        Addsuspect5.setBackground(new java.awt.Color(153, 153, 153));
        Addsuspect5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        Addsuspect5.setText("Log out");
        Addsuspect5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addsuspect5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Addsuspect3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Addsuspect4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Addsuspect1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Addsuspect2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Addsuspect)
                    .addComponent(Addsuspect5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(260, 260, 260))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addsuspect)
                    .addComponent(Addsuspect1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addsuspect2)
                    .addComponent(Addsuspect4))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Addsuspect3)
                    .addComponent(Addsuspect5))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 110, 770, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\VIJAY MORE\\Desktop\\dimple vjti notes\\third year\\lab\\SE\\2055138-dark-blue-abstract-background-resembling-wooden-texture-or-cracks.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddsuspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddsuspectActionPerformed
        setVisible(false);
        Add_suspect as=new Add_suspect();
        as.setVisible(true);
    }//GEN-LAST:event_AddsuspectActionPerformed

    private void Addsuspect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addsuspect1ActionPerformed
        setVisible(false);
        Add_Evidence ae=new Add_Evidence();
        ae.setVisible(true);
    }//GEN-LAST:event_Addsuspect1ActionPerformed

    private void Addsuspect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addsuspect2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Addsuspect2ActionPerformed

    private void Addsuspect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addsuspect3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Addsuspect3ActionPerformed

    private void Addsuspect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addsuspect4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Addsuspect4ActionPerformed

    private void Addsuspect5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addsuspect5ActionPerformed
        setVisible(false);
        Officer_log ol=new Officer_log();
        ol.setVisible(true);
    }//GEN-LAST:event_Addsuspect5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Officer_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Officer_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Officer_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Officer_home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Officer_home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addsuspect;
    private javax.swing.JButton Addsuspect1;
    private javax.swing.JButton Addsuspect2;
    private javax.swing.JButton Addsuspect3;
    private javax.swing.JButton Addsuspect4;
    private javax.swing.JButton Addsuspect5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
